### ISSUE TITLE
synthesize_speech on fixed input text 

### ISSUE THREAD

**Issue by CloudApiStudy** [UM-ARM-Lab/amazon_ros_speech#1]
Hi,

I come from a research team which works on bugs in real-world applications.

I want to make a report about a few potential performance improvement in your project.

In file `scripts/polly.py`, `synthesize_speech` is called to generate audio files in each run. However, its input is a fixed string in `call_polly(overload_str)`. This behavior increases execution time and brings unnecessary service cost. A caching mechanism could help such situation, e.g. save audio file on disk at first API call, and re-use that file later.

Perhaps someone might be able to confirm if these seem reasonable. Also, if you need any help, I'm happy to provide some code snippet for fixing.

If you are not offended by it, we may include your response as a percentage number (e.g. xx% of applications faces xx problem, and xx% of them confirms it) in our research paper.

Thanks.

**Comment by bsaund** [comment]
Glad you came across this project and I hope you find it useful! 

Your analysis is not quite correct. In usual behavior, this input to `call_polly` is `words`, from the `ros_str` argument. This can be (and usually is) different every query

`overload_str` is only used if the word limit is reached. This is just a safeguard in my code so that I don't accidentally charge my amazon account with 100,000 messages or something because of a mistake elsewhere if I were to call this service at a high frequency.


You are correct that I could cache the response of `overload_str`. Rather than save to disk, I'd just store it in memory, as that would be simpler. I've never come close to hitting this limit in practice.


I could also cache a dictionary of `words: response` so that I do not need to call Amazon's service for queries I've seen before. This could also save queries to the service. Under my current usage this might save a couple of cents total, so I am not concerned

**Comment by CloudApiStudy** [comment]
Thanks so much for your reply!

Yeah, `overload_str` would rarely be triggered during the runtime. It doesn't worth that much coding effort.

For word-wise caching, it might decrease audio quality a little bit. In typical text-to-speech networks, there will be a transition between words. The execution time would also increase a lot, as there's a cold-start time when calling the API. Maybe sentence or clause would be a better unit. But anyway, it's really a development-efficiency trade-off.

**Comment by bsaund** [comment]
Yes, entire sentences would be cached, not individual words.
